name: flutter_application_1
description: A new Flutter project
publish_to: "none" # Remove this line if publishing

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.8  # <-- this is correct

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
